name: Build libmahjong

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: gcc
          - toolchain: clang
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v30
      - name: Build using Nix
        run: |
          nix build -L '.#${{ matrix.toolchain }}'
